name: Packer Build Image
on:
  [push]
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build-image:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PKR_PROJECT_ID: ${{ vars.PKR_PROJECT_ID }}
      PKR_SOURCE_IMG_FAM: ${{ vars.PKR_SOURCE_IMG_FAM }}
      PKR_SSH_USERNAME: ${{ vars.PKR_SSH_USERNAME }}
      PKR_ZONE: ${{ vars.PKR_ZONE }}
      PKR_DISK_SIZE: ${{ vars.PKR_DISK_SIZE }}
      PKR_DISK_TYPE: ${{ vars.PKR_DISK_TYPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.DEV_GCP_SERVICE_IAM }}"
      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
      - name: Zip repository
        run: |
          zip -r webapp.zip .
          mv webapp.zip packer-setup/builds
      - name: Run `packer init`
        run: |
          cd packer-setup/builds
          packer init build.pkr.hcl
      - name: Test to make a template
        run: |
          gcloud compute instance-templates create testing-phase \
          --machine-type=e2-standard-2 \
          --boot-disk-size=100GB \
          --boot-disk-type=pd-balanced \
          --image=webapp-vm-image-1712153610 \
          --tags=webapp-instance \
          --network-interface=network=https://www.googleapis.com/compute/v1/projects/csye6225-anirban-002979520/global/networks/cloud-test-webapp-vpc,subnet=https://www.googleapis.com/compute/v1/projects/csye6225-anirban-002979520/regions/us-east1/subnetworks/webapp,network-tier=STANDARD \
          --service-account=csye6225-cloud@csye6225-anirban-002979520.iam.gserviceaccount.com \
          --scopes=logging-write,monitoring-write,pubsub,cloud-platform \
          --metadata=startup-script="#/bin/bash
          cd /opt/webapp/
          if [ -e .env ]; then
            sudo rm .env
          fi
          sudo tee -a .env <<EOF >/dev/null
          DB_NAME=webapp
          DB_PWD=rhxhabwhkp
          DB_USER=webapp
          DB_HOST=10.1.20.63
          WEB_PORT=8080
          DB_PORT=5432
          NODE_ENV=PRODUCTION
          EMAIL_EXPIRY=2
          EOF
          sudo chown csye6225:csye6225 .env
          " \
          --instance-template-region=us-east1
      - name: Attach new template to MIG
        run: |
          gcloud projects add-iam-policy-binding csye6225-anirban-002979520 \
          --member="serviceAccount:service-698091522680@gcp-sa-cloudbuild.iam.gserviceaccount.com" \
          --role="roles/compute.loadBalancerAdmin" --quiet
          gcloud projects add-iam-policy-binding csye6225-anirban-002979520 \
          --member="serviceAccount:testing-github@csye6225-anirban-002979520.iam.gserviceaccount.com" \
          --role="roles/iam.serviceAccountUser"
          gcloud projects add-iam-policy-binding csye6225-anirban-002979520 \
          --member="serviceAccount:testing-github@csye6225-anirban-002979520.iam.gserviceaccount.com" \
          --role="roles/iam.policyAdmin"
          gcloud compute instance-groups managed set-instance-template \
          webapp-mig \
          --template=projects/csye6225-anirban-002979520/regions/us-east1/instanceTemplates/testing-phase \
          --region=us-east1
      - name: Rolling action update instances
        run: |
          gcloud compute instance-groups managed rolling-action replace webapp-mig --region=us-east1 --replacement-method=recreate --max-surge=0
      # - name: Build packer Image
      #   run: |
      #     cd packer-setup/builds
      #     packer build build.pkr.hcl
