name: Packer Validate
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  validatePacker:
    runs-on: ubuntu-latest
    env:
      PKR_PROJECT_ID: ${{ vars.PKR_PROJECT_ID }}
      PKR_SOURCE_IMG_FAM: ${{ vars.PKR_SOURCE_IMG_FAM }}
      PKR_SSH_USERNAME: ${{ vars.PKR_SSH_USERNAME }}
      PKR_ZONE: ${{ vars.PKR_ZONE }}
      PKR_DISK_SIZE: ${{ vars.PKR_DISK_SIZE }}
      PKR_DISK_TYPE: ${{ vars.PKR_DISK_TYPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
      - name: Zip repository
        run: |
          zip -r webapp.zip .
          mv webapp.zip packer-setup/builds
        shell: bash
      - name: Run `packer init`
        run: |
          cd packer-setup/builds
          packer init build.pkr.hcl
      - name: Run `packer fmt`
        run: |
          cd packer-setup/builds
          packer fmt .
          git diff --exit-code build.pkr.hcl
      - name: Run `packer validate`
        run: |
          cd packer-setup/builds
          packer validate .
