name: Integration tests
on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - main

jobs:
  user-tests:
    if: (github.event.pull_request.merged == true)|| (github.event.action == 'opened') || (github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    steps:
      - name: Start Postgres and Create Dependencies
        run: |
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE USER ${{ vars.DB_USER }} WITH PASSWORD '${{ secrets.DB_PWD }}';"
          sudo -u postgres psql -c "CREATE DATABASE ${{ vars.DB_NAME }} WITH OWNER ${{ vars.DB_USER }};"
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: sudo npm test
        env:
          DB_USER: ${{ vars.DB_USER }}
          DB_PWD: ${{ secrets.DB_PWD }}
          DB_NAME: ${{ vars.DB_NAME }}
          WEB_PORT: ${{ vars.WEB_PORT }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
