name: Integration tests
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  user-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_database
          POSTGRES_USER: user
          POSTGRES_PASSWORD: cloud_2024
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          DB_USER: user
          DB_PWD: cloud_2024
          DB_NAME: test_database
