name: Integration tests
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  user-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: $DB_NAME
          POSTGRES_USER: $DB_USER
          POSTGRES_PASSWORD: $ {{ secrets.DB_PWD}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: npm ci

      - name: Run tests
        uses: npm test
