name: Github Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install & Compile Dependencies
        run: npm install
